name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ls
      run: ls api
    - name: Build the Docker api image
      run: docker build . --file api/Dockerfile --tag my-image-name:$(date +%s)
    - name: Build the Docker auth image
      run: docker build . --file auth/Dockerfile --tag my-image-name:$(date +%s)
